### ISSUE TITLE
Number of failed/ unstable controller attempts not reset when restarting simulation

### ISSUE THREAD

**Issue by Graham-EGI** [PMEC-OSU/FOSTWIN#11]
Not sure if this is the behavior we want, but when restarting a simulation through the UI, where the model isn't re-compiled, the number of faults/ unstable states that the controller is allowed to into before landing in the fault state isn't re-set.

Might become an issue if someone is using the realtime system to test optimizing parameters, where some of the tests land the controller in an unstable state.

**Comment by johannes-spinneken** [comment]
@Graham-EGI - is this still the case? We should have 3 "fault attempts" each time the simulation is started. This means 3 (set in the init script) times the state should change from normal -> stabilize -> safe damping -> normal, and then finally to fault.

**Comment by Graham-EGI** [comment]
Looks like I was wrong, operating as expected.
