### ISSUE TITLE
Please update docs on the ctrl state machine

### ISSUE THREAD

**Issue by Graham-EGI** [PMEC-OSU/FOSTWIN#12]
I made a rough start on the description for the docs for the ctrl state machine, but know it needs some work.

Section begins here: https://github.com/PMEC-OSU/FOSTWIN/blob/93b2bfb94c08a6e62f3c779fcf5a1c9994fe2f27/README.md?plain=1#L224

**Comment by johannes-spinneken** [comment]
Reviewed documentation. Closing this issue.
