### ISSUE TITLE
Frequency response in the journal paper

### ISSUE THREAD

**Issue by chen6991** [PMEC-OSU/FOSTWIN#14]
Hello @johannes-spinneken, I'm a PhD student working on this competition and I have a question about the frequency response in your paper (Fig. 7).

![FOSWEC paper_frequency response](https://user-images.githubusercontent.com/85910655/213832736-25b248c9-eddf-42db-bdb9-6909fa58268d.png)

I'm not sure what is the input and the output here, I guess this is based on the flap frame, and shows the frequency response from flap torque to flap velocity, is that correct? I tried to compare this to the bode plot I got from your SystemID model. The result shows that the two systems are totally different. Are we supposed to get the same system in this competition?

Besides, I tried to find out the frequency response of your wecSim model, and this seems to be different from the SystemID model (but somewhat similar). So I am also wondering how much difference is expected between the two models.

Thank you for your time and response.

**Comment by johannes-spinneken** [comment]
@chen6991 - Many thanks for posting your questions.

The frequency response presented in the paper and that used for the competition differ in a few ways. The frequency response presented in the paper focuses on the **global body dynamics** only. In contrast, the frequency response used for the competition also captures some **drive train dynamics**.

For the competition , please assume that the admittance model included in this repo https://github.com/PMEC-OSU/FOSTWIN is the correct admittance. 

In terms of inputs and outputs for this admittance, the below figure should help:

![image](https://user-images.githubusercontent.com/49918117/213896800-14d1145f-3057-4460-87e3-a01273c7ca32.png)

The input to the admittance is the motor torque (in the motor frame) and the output is the motor position (angle in the motor frame). For both the input and the output, the first element is the aft degree of freedom, and the second element is the bow degree of freedom.

In terms of the WECSim model, please note that this does not include all the dynamics of the device, and does also not include the drive train dynamics which are important to this competition. Think of the WECSim model as a simplified global dynamics model, that does not capture all the physics of the device. **For the purpose of the competition, please only use the SID model as noted in the instructions** [here](https://pmec-osu.github.io/FOSTWIN/) (see below for the key points). 

<img width="851" alt="image" src="https://user-images.githubusercontent.com/49918117/213896939-6bcb21ca-08b7-4106-90d8-ed489fbbc80d.png">

Just respond to this issue if you have further questions.

**Comment by chen6991** [comment]
@johannes-spinneken I see the differences between them, thank you for your response.
