### ISSUE TITLE
Triggers for state machine

### ISSUE THREAD

**Issue by rgcoe** [PMEC-OSU/FOSTWIN#16]
From today's information session: What do you use to detect instability and trigger the state machine?

**Comment by johannes-spinneken** [comment]
The images below show a typical sequence of the state machine catching an instability. This typical sequence shows
- Current rising very fast, and then reaching a certain threshold which triggers the stabilize state
- During the stabilize state, the bow and aft currents are set to zero for a short period of time
- Following the stabilize state, the state machine enters the safe state, which provides a simple damping controller which is known to be stable for the FOSTWIN
- Next, the state machine returns to the normal operating state, where the developer's absorption controller becomes active again
- After three instabilities, the state machine enters a fault state, from which is does not recover

The settings for the various thresholds that trigger the state machine are here:
https://github.com/PMEC-OSU/FOSTWIN/blob/4e9a8273d53151456cabb7e711ff6216fac4f4a3/initModels_GUI.m#L206-L212

![StateMachine](https://user-images.githubusercontent.com/49918117/217083324-e141e394-3515-4802-a99f-1a7bdc1fa1aa.png)

![image](https://user-images.githubusercontent.com/49918117/217083368-55b9b6d1-1ab2-4503-b819-9394e07daa6f.png)

Some further remarks:
- The key purpose of the state machine is to avoid instabilities on the Speedgoat real-time system. Such instabilities will crash the Simulink simulation, and it becomes very difficult to debug the issues causing instabilities
- With the state machine in place, instabilities are caught, and can be debugged based on the run data 
- The low pass filters for the signals entering the state machine (see image below) do NOT affect the absorption controller signal path. These low pass filters are only introduced to avoid the state machine triggering a fault state for short spikes in the current or velocity signals,

![image](https://user-images.githubusercontent.com/49918117/217084522-ae06094c-fc05-48c9-a8ea-be40a4a32d5e.png)

The state machine state is included in the ctrl2Twin signal bus, signal "state". This is defined as an enum with underlying type int32.

https://github.com/PMEC-OSU/FOSTWIN/blob/4e9a8273d53151456cabb7e711ff6216fac4f4a3/initModels_GUI.m#L180-L193

The normal state corresponds to ctrlNormal, which is equivalent to an integer value of 2.
