### ISSUE TITLE
Change/affect drive train dynamics

### ISSUE THREAD

**Issue by rgcoe** [PMEC-OSU/FOSTWIN#18]
From today's information session: Can we change/affect the drive train dynamics?

**Comment by gbacelli** [comment]
can you be more specific? the dynamics of the physical system or the model?

**Comment by johannes-spinneken** [comment]
The admittance is shown in the figure below:

![image](https://user-images.githubusercontent.com/49918117/217070337-b00bf168-0b99-4305-ac52-4c7016712d59.png)

The admittance model captures two key effects

**1.  Global body hydrodynamics** (based on cases 164-168)
- The global body hydrodynamics dominate in the frequency range ~0.1 … 1Hz
- Includes effects such as flap inertia, added mass and radiation damping 


**2.  Drive train dynamics** (based on case 226)
- The drive train, from applying motor torque to measured motor angle, is not “ideal” (ideal would be if dynamics were excluded)
- Experimental data showed drive train resonance at approx. 53…56 Hz
- This type of resonance is common for all models, incl. tank and ocean scale models. Typical 20-60Hz at model scale; lower at full scale. 
- Will affect closed-loop behavior, and can lead to controller instabilities if loop gain too high at high frequencies (drive train resonance)

The drive train resonance is an inherent part of the real mechanical system. It can only be altered via mechanical re-design. For many projects of this nature (e.g. tank-scale model testing design, design of a WEC for ocean-going operation), the control engineer needs to work with what has been provided by the mechanical engineering design team. The drive train (including its resonance) for the FosTWIN is considered "workable", as a stable absorption controller can be designed. However, the controller may be limited in terms of loop gain at high frequencies, which is common for many real-world controllers.

For real-world projects, it is good practice for the mechanical engineering team and the control team to debrief after commissioning, to ensure that any issues in the controller design can be addressed (if possible) in the next iteration for the mechanical design.
