### ISSUE TITLE
WAMIT excitation force phasing

### ISSUE THREAD

**Issue by johannes-spinneken** [PMEC-OSU/FOSTWIN#3]
@bretbosma I believe I found a first issue as to why SID and wecSim give different results. There are likely more differences, but this particular issue should probably be resolved first.

I compared the excitation force from the "excitationWAMIT.mat" file with that from the h5 file used in wecSim. The Matlab code used for the comparison is pasted at the end of this issue. This code will need wecSim on the path for the readBEMIOH5 function.

The results:

![image](https://user-images.githubusercontent.com/49918117/174872848-54f26936-e432-4111-8092-15d2e96c5d4c.png)

![image](https://user-images.githubusercontent.com/49918117/174872899-3e8cc99c-f781-4f80-a658-78fceb3e1be5.png)

![image](https://user-images.githubusercontent.com/49918117/174872946-d4c150cc-921f-40f8-b122-1d2ae96c7aa2.png)

Observations:
* the comparison looks good for the abs 
* for the real and imag, it seems the phase is "scrambled" (for lack of a better word) for the aft flap for the SID case. The behavior of this excitation force does not look physical. I suspect something went wrong when the "excitationWAMIT.mat" file was created

Possible actions:
* Replace the  "excitationWAMIT.mat" file with a corrected version (if found to be incorrect)
* Remove the  "excitationWAMIT.mat" file, and read from the h5 file as in the code below. If going this route, we should extract the required h5 read code from the wecSim example, and have a little helper function in our repo (to avoid needing a wecSim install on the path for the SID option).

@bretbosma - any views?

```
% check excitation force between WAMIT mat file for SID and h5 file for
% WecSim

clearvars; close all; clc;

% SID excitation force from WAMIT
sid = load('excitationWAMIT.mat');

dofPitch = 5;
rho = 1020;
g = 9.81;

% use wecSim script to read H5 file
hydroWecSimFlapBow = readBEMIOH5('hydroData/foswec.h5',1,0); % bow flap is body 1
hydroWecSimFlapAft = readBEMIOH5('hydroData/foswec.h5',3,0); % aft flap is body 3

wecSimFexBowPitch =  rho*g* (squeeze(hydroWecSimFlapBow.hydro_coeffs.excitation.re(dofPitch,1,:)) ...
                        + 1i*squeeze(hydroWecSimFlapBow.hydro_coeffs.excitation.im(dofPitch,1,:)));

wecSimFexAftPitch =  rho*g* (squeeze(hydroWecSimFlapAft.hydro_coeffs.excitation.re(dofPitch,1,:)) ...
                        + 1i*squeeze(hydroWecSimFlapAft.hydro_coeffs.excitation.im(dofPitch,1,:)));

figure
subplot(2,1,1)
plot(sid.w, abs(sid.FexBowPitch))
hold on
plot(hydroWecSimFlapBow.simulation_parameters.w, abs(wecSimFexBowPitch))
ylabel('Fex Pitch Bow (Nm/m)')
xlabel('t (s)')
title('Abs')
legend('SID','wecSim')

subplot(2,1,2)
title('Abs')
plot(sid.w, abs(sid.FexAftPitch))
hold on
plot(hydroWecSimFlapAft.simulation_parameters.w, abs(wecSimFexAftPitch))
ylabel('Fex Pitch Aft (Nm/m)')
xlabel('t (s)')
legend('SID','wecSim')

figure
subplot(2,1,1)
plot(sid.w, real(sid.FexBowPitch))
hold on
plot(hydroWecSimFlapBow.simulation_parameters.w, real(wecSimFexBowPitch))
ylabel('Fex Pitch Bow (Nm/m)')
xlabel('t (s)')
title('Real')
legend('SID','wecSim')

subplot(2,1,2)
plot(sid.w, real(sid.FexAftPitch))
hold on
plot(hydroWecSimFlapAft.simulation_parameters.w, real(wecSimFexAftPitch))
ylabel('Fex Pitch Aft (Nm/m)')
xlabel('t (s)')
legend('SID','wecSim')

figure
subplot(2,1,1)
plot(sid.w, imag(sid.FexBowPitch))
hold on
plot(hydroWecSimFlapBow.simulation_parameters.w, imag(wecSimFexBowPitch))
ylabel('Fex Pitch Bow (Nm/m)')
xlabel('t (s)')
title('Imag')
legend('SID','wecSim')

subplot(2,1,2)
plot(sid.w, imag(sid.FexAftPitch))
hold on
plot(hydroWecSimFlapAft.simulation_parameters.w, imag(wecSimFexAftPitch))
ylabel('Fex Pitch Aft (Nm/m)')
xlabel('t (s)')
legend('SID','wecSim')

```

**Comment by bretbosma** [comment]
@johannes-spinneken I'd say we should read directly from the .h5 file if it is not too much trouble with the helper script.

I found the code I used to generate the excitationWAMIT.mat file.  This is run after running and old version of bemio.m.  Perhaps index 17 is not correct for the Aft float.  At any rate the method should be updated if we go this route.

```
% clear; clc; close all
rho = 1000;
g = 9.8065;


FexBowPitch_mag = rho*g*squeeze(hydro.ex_ma(5,1,:));
FexBowPitch_pha = squeeze(hydro.ex_ph(5,1,:));
FexBowPitch = FexBowPitch_mag .* exp(1i*FexBowPitch_pha);


FexAftPitch_mag = rho * g * squeeze(hydro.ex_ma(17,1,:));
FexAftPitch_pha = rho * g * squeeze(hydro.ex_ph(17,1,:));
FexAftPitch = FexAftPitch_mag .* exp(1i*FexAftPitch_pha);

w = hydro.w;
save('excitationWAMIT.mat','FexAftPitch','FexBowPitch','w')

figure
subplot(211)
plot(hydro.w/(2*pi),abs(FexAftPitch))
hold on
plot(hydro.w/(2*pi),abs(FexBowPitch))
legend('Aft','Bow')

subplot(212)
plot(hydro.w/(2*pi),angle(FexAftPitch))
hold on
plot(hydro.w/(2*pi),angle(FexBowPitch))
xlabel('f(Hz)')
```

**Comment by johannes-spinneken** [comment]
@bretbosma - thanks for posting the code. The bug here is actually the multiplication with rho*g in the calculation of FexAftPitch_pha.

Agreed, let's take the excitation forcing directly from the h5 file in the future to avoid the need for a separate .mat file.

**Comment by johannes-spinneken** [comment]
Fixed in the latest version; closing the issue.
