### ISSUE TITLE
Viscous and linear drag for FOSTWIN WecSim simulations

### ISSUE THREAD

**Issue by johannes-spinneken** [PMEC-OSU/FOSTWIN#7]
@bretbosma @ryancoe 

The linear and quadratic damping used for the WecSim FOSTWIN both seem a little high. 

https://github.com/PMEC-OSU/FOSTWIN/blob/6824521f0917a5abb44ee8661a1dbe85cd944b6b/wecSimInputFile.m#L74-L75

Is there any documentation / reporting available for the data analysis that led to those coefficients?

**Comment by bretbosma** [comment]
@johannes-spinneken I believe this was based on FOSWEC1 results, so an earlier version of the hardware.  If there are values that match the experimental data better, I'd say go with those.

**Comment by johannes-spinneken** [comment]
Needed to update linearDamping(5) to linearDamping(5,5), as this is now a (6x6) matrix in WecSim. Closing this issue.
