### ISSUE TITLE
SID vs. WecSim comparision: Case A

### ISSUE THREAD

**Issue by johannes-spinneken** [PMEC-OSU/FOSTWIN#8]
The purpose of this issue is to track comparisons between the FOSTWIN SID and WecSim results. This issue covers Case A: Hs=0.136m and Tp = 2.61m

**Comment by johannes-spinneken** [comment]
@aliSHaider made a comparison between the WecSim and SID implementations of the FOSTWIN device, and found some significant differences. 

Review of the code base uncovered the following issues:
- An incorrect phasing of the aft excitation force (via a .mat file) used for SID simulations. See #3. This issue will lead to major differences, and requires a critical fix. 
- An incorrect scaling of the Jonswap spectrum for SID, see #4. This will lead to ~25% difference for gamma=3.3
- An inconsistent Jonswap gamma between SID and WecSim, see #5.
- Potentially some inconsistencies in the generation of irregular wave excitation force time series for SID, see #6  
- Some (potential) uncertainty concerning the linear and viscous drag coefficients #7 

At the time of writing this comment, the issues noted above still persist in the GitHub version of the code, but have been addressed on a local code version that produced the below results.

For the present comparison:
- Hs = 0.136m and Tp = 2.61m
- 1800s run time
- Ts = 1/100s for both SID and WecSim
- linear damping = 4.7, and Cd = 5 (seems a little more realistic than ~20)

**Time domain overview**

![image](https://user-images.githubusercontent.com/49918117/175130732-979c51d5-efa3-489a-9dd7-8f0be684484b.png)

- WecSim and SID use different ways of discretizing the wave spectrum; they will hence have different wave components with different random phasing, and a comparison in the time domain is difficult 
- Having said this, the general trends for all variables look similar
- @bretbosma The angles shown are the flap angles, not the motor angles. In the case of SID, this is obtained by dividing the motor angles by N (3.75). For WecSim, they are obtained by dividing the PTO positions by N. Does the gear ratio N enter WecSim, to make sure that the flap position (angle) and velocity are less than the PTO position/velocity?

**Excitation force**
![image](https://user-images.githubusercontent.com/49918117/175131647-f28242ae-98bf-41cb-95f7-1f55acd89215.png)

- The above figure shows the excitation force as a probability of exceedance, based on an up-crossing analysis of the time series
- The agreement between SID and WecSim is very good: this IS expected, as the two results are entirely based on the same WAMIT data. The excitation force is NOT affected by any device dynamics, and should hence be identical. 
- The small differences in the tail of the distribution are likely due to different phase realizations 
- To get the two excitation forces to agree as shown, all of the above issues had to be addressed - for the current code on GitHub, the excitation forces are VERY different, which is likely the main cause for the differences @aliSHaider observed

**Angles**
 
![image](https://user-images.githubusercontent.com/49918117/175132380-32e5e2f0-c332-4311-833a-c116c0df1f64.png)

- The comparison between WecSim and SID is fairly good, particularly for the bow angle
- These results will depend on the drag coefficients, so further investigation should hold until issue #7 has been addressed
- Either way, these comparisons are a significant improvement over the previous comparisons prior to fixing several issues

**Comment by bretbosma** [comment]
@johannes-spinneken WEC-Sim does not know anything about the gear ratio between the flap and motor.  It only calculates flap related parameters.

**Comment by johannes-spinneken** [comment]
@bretbosma Looking at the relevant code sections:

![image](https://user-images.githubusercontent.com/49918117/175138333-865d5463-039a-4cb7-8683-0bea7568c0c3.png)
For SID:
- Excitation force is in "flap" frame, and gets divided by N to be in "motor" frame
- Motor current * kt is the motor torque in the motor frame
- The torque summing junction is in the motor frame

![image](https://user-images.githubusercontent.com/49918117/175139072-2007f635-6b17-4e08-b673-11c193e2d109.png)
For WecSim
- You note everything is in the "flap" frame
- I assume Kt is the same between WecSim and SID
- If that is the case, the current for WecSim would need to be much larger, as it needs to produce 3.75 times as much torque (if in flap frame). Is this correct?

**Comment by bretbosma** [comment]
@johannes-spinneken Yes, I think you are right.  The motor torque on the shaft (Cur_Bow and Cur_Aft) for the WEC-Sim case will need to be transferred through the gear ratio to be input to the flap, so a multiplication by N on both flap torque lines seems right.

**Comment by johannes-spinneken** [comment]
@bretbosma @ryancoe

Based on the available FOSTWIN reporting, some of the gearing is not clear to me. To summarize:
- the system is driven by an Allied Motion MF0150025-C0X motor, with 3:1 gearing (Note: I cannot find a datasheet for this motor on the Allied Motion Website)
- the FOSTWIN system has a 3.75 gearing via the drive belt / pulley 
- based on Figure E-8 in the testing report, the torque constant is Kt = 0.943 Nm/A

**My question**: Is this torque constant noted in the motor frame or the flap frame? In other words, does a current of 1A apply 0.943 Nm of torque on the flap, or 3.75*0.943Nm = 3.53Nm on the flap.

Based on the power equations (see e.g. eq. (8) in the testing report), I assume that the gearing of 3.75 is already included in the torque constant. Is this correct?

If the gearing is already included in the torque constant, then I believe some of the SID implementation (see two comments above) is not currently correct, as the torque coming out of the Kt gain block would be in the flap frame, not in the motor frame.

**Comment by rgcoe** [comment]
@stespenc83 @dforbush2 @gbacelli may be able to add to this

From Table 2-1 in the report (https://doi.org/10.2172/1717884), that the gear ratio is 3.75. As an example, here's some code that I found when working with some other collaborators (data available here: https://dx.doi.org/10.15473/1782587):

<details>
  <summary>Example MATLAB code</summary>

```matlab
clc
clear
close all

%% load data (make sure its in your search path)

load('FOSWEC_220.mat')

T_rep = 30;     % period over which controller gains are constant

%% Motor and controller

clc

close all
figure('name','Motors and controllers')

flap_names = {'bow','aft'};

tot_rows = 3;

plot_row = 0;

for ii = 2*plot_row+[1:length(flap_names)]
    
    dat_to_plot = dat.snl.(flap_names{ii-2*plot_row});
    
    ax(ii) = subplot(tot_rows,2,ii);
    title(ax(ii),flap_names{ii})
    hold on
    grid on
    plot(ax(ii),dat_to_plot.t, dat_to_plot.KP_used,...
        'DisplayName', 'Kp') % control gain propotional to position
    plot(ax(ii),dat_to_plot.t, dat_to_plot.KD_used,...
        'DisplayName', 'Kd')% control gain propotional to velocity
    legend(ax(ii),'Interpreter','latex')
end

plot_row = 1;

for ii = 2*plot_row+[1:length(flap_names)]

    dat_to_plot = dat.snl.(flap_names{ii-2*plot_row});
    
    ax(ii) = subplot(tot_rows,2,ii);
    
    hold on
    grid on
    plot(ax(ii),dat_to_plot.t, dat_to_plot.w_m,...
        'DisplayName', 'Motor velocity')
    plot(ax(ii),dat_to_plot.t, dat_to_plot.th_m,...
        'DisplayName', 'Motor position')
    legend(ax(ii),'Interpreter','latex')
end

plot_row = 2;

for ii = 2*plot_row+[1:length(flap_names)]

    dat_to_plot = dat.snl.(flap_names{ii-2*plot_row});
    
    ax(ii) = subplot(tot_rows,2,ii);
    
    hold on
    grid on
    
    plot(ax(ii),dat_to_plot.t, dat_to_plot.tau_I_m,...
        'DisplayName', 'Motor torque ($\tau = K_t I$)')
    
%     plot(ax(ii),dat_to_plot.t, dat_to_plot.tau_I_m*dat_to_plot.N,...
%         'DisplayName', 'Another way to plot flap torque')
    
    plot(ax(ii),dat_to_plot.t, dat_to_plot.tau_I_f,...
        'DisplayName', 'Flap torque ($\tau = K_t I N$)')
    
    legend(ax(ii),'Interpreter','latex')
end

linkaxes(ax,'x')

for ii = length(ax)-1:length(ax)
    xlabel(ax(ii),'Time [s]')
end

%% Flap and motor motion

figure('name','Flap and motor motion')
flap_names = {'bow','aft'};


ax(1) = subplot(2,1,1);
ylabel('Flap position [rad]')
title('bow')
hold on
plot(ax(1),dat.snl.bow.th_m/dat.snl.bow.N,'DisplayName','th\_m / N')
plot(ax(1),dat.snl.bow.th_f,'DisplayName','th\_f')
plot(ax(1),detrend(dat.snl.bow.ssi_m,'constant')/dat.snl.bow.N,...
    'DisplayName','ssi\_m / N')
plot(ax(1),detrend(dat.snl.bow.ssi_f,'constant'),...
    'DisplayName','ssi\_f')

ylim([-0.5,0.5])

legend()

ax(2) = subplot(2,1,2);
ylabel('Flap veloocity [rad/s]')
hold on
plot(ax(2),dat.snl.bow.w_m/dat.snl.bow.N,...
    'DisplayName','w\_m / N')
plot(ax(2),dat.snl.bow.w_f,...
    'DisplayName','w\_f')
plot(ax(2), gradient(dat.snl.bow.th_f,1e-3),...
    'DisplayName','gradient(th\_f)')

ylim([-1.5,1.5])
xlabel('Sample')

linkaxes(ax,'x')

legend()

%% Device orientation

figure('name','Device orientation')

clear ax
ax(1) = subplot(2,1,1);
hold on
grid on
theta_x = unwrap(dat.snl.imu.IMU_thx*pi/180)*180/pi;
theta_x = theta_x - mean(theta_x);
plot(dat.snl.hull.t, theta_x,...
        'DisplayName', '$\theta_x$')
    
theta_y = dat.snl.imu.IMU_thy - mean(dat.snl.imu.IMU_thy);
plot(dat.snl.hull.t, theta_y,...
        'DisplayName', '$\theta_y$')
    
plot(dat.snl.hull.t, dat.snl.imu.IMU_thz,...
        'DisplayName', '$\theta_z$') % TODO: remove drift by filtering

legend(ax(1),'Interpreter','latex')
ylabel(ax(1),'Orientation [deg]')


ax(2) = subplot(2,1,2);
hold on
grid on

plot(dat.snl.hull.t, detrend(dat.snl.imu.IMU_wx,'constant'),...
        'DisplayName', '$\omega_x$')
plot(dat.snl.hull.t, detrend(dat.snl.imu.IMU_wy,'constant'),...
        'DisplayName', '$\omega_y$')
plot(dat.snl.hull.t, detrend(dat.snl.imu.IMU_wz,'constant'),...
        'DisplayName', '$\omega_z$')

legend(ax(2),'Interpreter','latex')
ylabel(ax(2),'Rotational velocity [deg/s]')

linkaxes(ax,'x')

xlabel(ax(2),'Time [s]')

%% Waves

% Wave gauges to consider (see Fig 2-12 in SAND2020-11695)
% each cell includes probes at the same location along the wave
% propagation path
wgind = {1;2;3;4;6:9;12:14};  

nx = length(wgind);

clear eta
for ii = 1:nx
    for jj = 1:length(wgind{ii}) 
        eta{ii}(:,jj) = dat.osu.(sprintf('wg%i',wgind{ii}(jj)));
    end
end

figure('name','Wave gauges')
for ii = 1:nx
    ax(ii) = subplot(nx,1,ii);
    hold on
    grid on
    for jj = 1:size(eta{ii},2)
        plot(dat.osu.timeSNL, eta{ii}(:,jj),...
            'DisplayName',sprintf('wg%i',wgind{ii}(jj)));
    end
    legend(ax(ii))
    ylabel('Free surf. elev. [m]')
end

linkaxes(ax,'x')
xlabel('Time [s]')

%% Compare up-wave wave gauges

figure('name','Wave gauge comparison')
hold on

wgind2 = {1;2;3;4};
nx = length(wgind2);
clear eta
for ii = 1:nx
    for jj = 1:length(wgind2{ii}) 
        eta{ii}(:,jj) = dat.osu.(sprintf('wg%i',wgind2{ii}(jj)));
        plot(dat.osu.timeSNL, eta{ii}(:,jj),...
            'DisplayName',sprintf('wg%i',wgind2{ii}(jj)));
    end
end

legend()
ylabel('Free surf. elev. [m]')
xlabel('Time [s]')
```
</details>

**Comment by stespenc83** [comment]
The motor has a datasheet torque constant Kt of (1.021 Nm/A, +/-10%). In the testing report Ryan linked (Figure E-8), we found Kt= 0.943 Nm/A for the motor itself, which is within 10%. The gear ratio according to Table 2-1 is 75/20=3.75. So 1A at the motor will produce 3.53Nm on the flap.

I do see that on page 73 we list the gearing as 3:1. At one point in the design we might have had the ratio as 75/25=3. I believe we went larger shortly before testing due to needing more damping. Flap damping to motor damping scales with N^2 so even this small change is pretty impactful 9~>14 (56% more).

e.q. (8) in the testing report is correct. All values used are in the motor frame, no gearing is necessary. Current is measured for the motor and motor angular velocity is measure by encoders on the motor.

**Comment by stespenc83** [comment]
Re-reading the text around e.q. (8), I stand corrected. The text says these are flap velocities, they should be motor velocities, base on the preceding line "Mechanical power calculated at the motor shaft is"

**Comment by johannes-spinneken** [comment]
@stespenc83 Thanks for this! The text in the paper/report saying "flap velocities" was the main point of confusion - if this reads "motor velocities", then the gearing treatment is consistent.

**Comment by rgcoe** [comment]
Thanks guys and sorry for the misinformation in the report.

**Comment by johannes-spinneken** [comment]
Thanks @ryancoe and @stespenc83 for the various clarifications. To conclude this issue, I am summarizing the various conventions and gearing treatments here.

### FOSWEC SID model

- see below image for current Simulink implementation
- the excitation force (from e.g. WAMIT) is in the flap frame. This gets divided by the gear ratio (1/N), so that the excitation force is expressed in the motor shaft frame at the summing junction 
- the motor current multiplied with the torque constant Kt yields the applied motor torque in the motor shaft frame
- the admittance is from motor torque -> motor position 
- the outputs of the SID model are the bow and aft positions in the **motor shaft frame**

![image](https://user-images.githubusercontent.com/49918117/179045061-e8595a86-41c0-4527-ab4f-943a14ae3168.png)

- considering the controller model, the position signals entering are still in the **motor shaft frame**
- this also means that the control signals (e.g. damping for damping control) are in the **motor shaft frame**
- @bretbosma I believe this is slightly unconventional, as this means that the controller coefficients (e.g. damping) are not in the same frame as the excitation force or radiation damping. The currently implemented convention also differs from the definition of the controller terms in the experimental campaign (see e.g. equation 7 in the paper), where all controller coefficients are defined in terms of flap (not motor shaft) quantities. 
- **_I suggest changing the SID / controller model, such that the controller parameters are in the flap frame._**
- @bretbosma - there also seems to be a bug here, where the input to the SID admittance is in the order aft/bow (forces), but the output is in the order bow/aft (positions). I will correct this, and commit to GitHub. 

![image](https://user-images.githubusercontent.com/49918117/179047933-b6b77f74-e0fc-4005-9f69-3bda454dcc99.png)

### FOSWEC WEC-Sim model

- in the WEC-Sim model, the bow and aft current enter the model in the motor shaft frame
- however, the excitation force is processed internally (using the h5 file), and hence in the flap frame 
- in my view, this is inconsistent, and the motor torque (I*Kt) should be translated into the flap frame (*N) before applying this torque to PTO(1) and PTO(2)
- further, the position results produced by the WEC-Sim model are in the flap frame; they enter the same controller model as the SID position results, but are in different frames. Hence, damping is expressed in the motor frame for SID, but flap frame for WEC-Sim
- @bretbosma - I will update the code to ensure that treatment of the frames is consistent between the models. Please check my revised code once committed. 

![image](https://user-images.githubusercontent.com/49918117/179050001-e8490962-a203-4f5b-8d25-e8247f23b0f0.png)

**Comment by rgcoe** [comment]
Thanks for the summary @johannes-spinneken. Shall we close this issue?

**Comment by johannes-spinneken** [comment]
@ryancoe I have prepared an update presentation for our call next week, with some remaining questions. I will update this issue after our call next week and close then.

**Comment by johannes-spinneken** [comment]
Made all required changes to be consistent between SID models and WecSim. Closing this issue.
